feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

ribbon:
  okhttp:
    enabled: true

logging:
  level:
    me:
      linbo:
        demo:
          web:
              consumer:
                service:
                  others: error