server:
  port: 18080


spring:
  cloud:
    zookeeper:
      enabled: true
      connect-string: localhost:2181

  redis:
    host: localhost
    port: 6379

logging:
  level:
    me:
      linbo:
        web:
          common: info
    org:
      redisson:
        command: info
