server:
  port: 10002

spring:
  security:
    user:
      name: user
      password: 123
  redis:
    host: localhost
    database: 0

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:10000/accounts

logging:
  level:
    org:
      springframework:
        security: DEBUG