server:
  port: 10000

spring:
  cloud:
    config:
      fail-fast: false
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:test
    username: sa
    password:

# 官方配置说明 https://mp.baomidou.com/config
mybatis-plus:
  mapper-locations: classpath:/mybatis/**Mapper.xml
  type-aliases-package: me.linbo.web.api.model.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    me:
      linbo:
        web:
          demo:
            mapper: debug
