spring:
  security:
  #  访问gateway的用户密码
    user:
      name: admin
      password: admin
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTIONS
      routes:
      - id: web-api-provider
        uri: lb://web-api-provider
        predicates:
        - Path=/provider/**
        filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/defaultFallback'
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2

      - id: web-api-consumer
        uri: lb://web-api-consumer
        predicates:
        - Path=/consumer/**
        filters:
        - StripPrefix=1

      - id: baidu
        uri: https://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
        - StripPrefix=1

      httpclient:
        ssl:
          use-insecure-trust-manager: true

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000



logging:
  level:
    org:
      springframework:
        cloud:
          gateway: info
