spring:
  cloud:
    gateway:
      routes:
      - id: web-api-provider
        uri: lb://localhost:10000
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
        predicates:
        - Path=/api/**

      - id: web-api-consumer
        uri: lb://localhost:10001
        predicates:
          - Path=/api/**

  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 2000