server:
  port: 10000

spring:
  application:
    name: "@pom.artifactId@"
  profiles:
    active: "@profile.active.id@"

  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 2000

  cloud:
    gateway:
      routes:
      - id: web-api
        uri: lb://localhost:10000
        predicates:
          - Path=/api/**
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        prefer-agent-address: true
        ip-address: ${spring.cloud.client.ip-address}
        tags: ${spring.profiles.active}
