spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 2000

  cloud:
    gateway:
      routes:
      - id: web-api
        uri: lb://localhost:10000
        predicates:
          - Path=/api/**
