spring:
  redis:
    host: 172.21.109.247
    port: 6379
    password:
    timeout: 2000

  cloud:
    gateway:
      routes:
      - id: web-api
        uri: lb://localhost:10000
        predicates:
          - Path=/api/**
